package com.laerdal.api.tests;

import app.getxray.xray.junit.customjunitxml.annotations.Requirement;
import app.getxray.xray.junit.customjunitxml.annotations.XrayTest;
import com.laerdal.api.clients.AuthClient;
import com.laerdal.api.clients.TtsClient;
import com.laerdal.api.data.TtsTestData;
import com.laerdal.api.model.TtsRequest;
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import io.qameta.allure.TmsLink;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Auto-generated by /ready-for-testing from LBVOICESER-1330 ("TTS POST API").
 * Plan approved at Gate 1 with the response-time guard removed per reviewer edit —
 * four negative (400) acceptance-criteria cases.
 */
@Feature("TTS Post API")
@XrayTest(key = "LBVOICESER-1342")
@Requirement({"LBVOICESER-1330"})
@TmsLink("LBVOICESER-1330")
class Tts1330PostApiTest {

    @Test
    @DisplayName("AC1 - Request without Authorization header returns 400")
    @Description("POST /tts/v1/tts with a valid body but no Authorization header -> HTTP 400.")
    void missingAuthorizationReturns400() {
        TtsClient.synthesizeWithoutAuth(TtsTestData.random())
                .then().statusCode(400);
    }

    @Test
    @DisplayName("AC2 - Empty JSON body returns 400")
    @Description("POST with an empty body {} -> HTTP 400.")
    void emptyBodyReturns400() {
        String token = AuthClient.defaultToken();
        TtsClient.synthesize(token, new TtsRequest())
                .then().statusCode(400);
    }

    @Test
    @DisplayName("AC3 - Missing voice field returns 400")
    @Description("POST with only speechText (voice omitted) -> HTTP 400.")
    void missingVoiceFieldReturns400() {
        String token = AuthClient.defaultToken();
        TtsClient.synthesize(token, new TtsRequest(null, "Missing voice field test"))
                .then().statusCode(400);
    }

    @Test
    @DisplayName("AC4 - Missing speechText field returns 400")
    @Description("POST with only voice (speechText omitted) -> HTTP 400.")
    void missingSpeechTextFieldReturns400() {
        String token = AuthClient.defaultToken();
        TtsClient.synthesize(token, new TtsRequest("Male_Davis_Terrified_1", null))
                .then().statusCode(400);
    }
}
