package com.laerdal.api.tests;

import static org.hamcrest.Matchers.lessThan;

import app.getxray.xray.junit.customjunitxml.annotations.Requirement;
import app.getxray.xray.junit.customjunitxml.annotations.XrayTest;
import com.laerdal.api.clients.AuthClient;
import com.laerdal.api.clients.TtsClient;
import com.laerdal.api.config.EnvConfig;
import com.laerdal.api.data.TtsTestData;
import com.laerdal.api.model.TtsRequest;
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import io.qameta.allure.TmsLink;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Auto-generated by /ready-for-testing from LBVOICESER-1335 ("TTS STREAM POST API").
 * Covers POST {@code /tts/v1/tts-stream}. Per the ticket's acceptance criteria, a missing
 * {@code voice} or {@code speechText} field returns HTTP 200 (unlike the non-stream
 * endpoint in LBVOICESER-1330, where the same omissions return 400) — asserted exactly as
 * written in the ticket.
 */
@Feature("TTS Stream Post API")
@XrayTest(key = "LBVOICESER-1348")
@Requirement({"LBVOICESER-1335"})
@TmsLink("LBVOICESER-1335")
class TtsStreamPostApiTest {

    @Test
    @DisplayName("AC1 - Request without Authorization header returns 400")
    @Description("POST /tts/v1/tts-stream with a valid body but no Authorization header -> HTTP 400.")
    void missingAuthorizationReturns400() {
        TtsClient.synthesizeStreamWithoutAuth(TtsTestData.random())
                .then().statusCode(400);
    }

    @Test
    @DisplayName("AC2 - Empty JSON body returns 400")
    @Description("POST with an empty body {} -> HTTP 400.")
    void emptyBodyReturns400() {
        String token = AuthClient.defaultToken();
        TtsClient.synthesizeStream(token, new TtsRequest())
                .then().statusCode(400);
    }

    @Test
    @DisplayName("AC3 - Missing voice field returns 200")
    @Description("POST with only speechText (voice omitted) -> HTTP 200.")
    void missingVoiceFieldReturns200() {
        String token = AuthClient.defaultToken();
        TtsClient.synthesizeStream(token, new TtsRequest(null, "Missing voice field test"))
                .then().statusCode(200);
    }

    @Test
    @DisplayName("AC4 - Missing speechText field returns 200")
    @Description("POST with only voice (speechText omitted) -> HTTP 200.")
    void missingSpeechTextFieldReturns200() {
        String token = AuthClient.defaultToken();
        TtsClient.synthesizeStream(token, new TtsRequest("Male_Davis_Terrified_1", null))
                .then().statusCode(200);
    }

    @Test
    @DisplayName("Performance - Response within configured timeout")
    @Description("POST a valid stream request and assert only that it returns within EnvConfig.timeoutMs(); no status assertion so it stays valid regardless of backend availability.")
    void responseTimeWithinTimeout() {
        String token = AuthClient.defaultToken();
        TtsClient.synthesizeStream(token, TtsTestData.random())
                .then().time(lessThan((long) EnvConfig.timeoutMs()));
    }
}
